messages:
  responses:
    start: "Данный бот предназначен для помощи в изучении иностранных слов. Пользователи могут проходить тесты на основании добавленных или пакетов слов."
    word_done: "✅"
    word_miss: "❌"
    test_done: "Тест закончен, правильных ответов:"
    no_packages: "У вас пока нет пакетов"
    choose_package_to_start: "Выберите пакет для начала теста"
    choose_package_to_delete: "Выберите пакет, который хотите удалить"
    insert_package: "Введите пары слов разделенные двоеточием, каждая пара слов должна быть на новой строке"
    insert_package_name: "Введите название пакета"
    package_added: "Пакет добавлен"
    package_deleted: "Пакет удален"
    chosed_package: "Выбран пакет"
    deleted_package: "Удалён пакет"
  errors:
    unknown_command: "Я не знаю такую команду"
    start_lesson: "Сначала начните урок"
    small_package: "Слишком маленький пакет. Пакет должен содеражать не менее 4 пар слов"
    empty_strings: "В пакете были найдены пустные строки, попробуйте ввести снова"
    already_exist: "Такой пакет уже существует"
    dosnt_work: "Пока не работает"
