messages:
  responses:
    start: "Приветсвенное сообщение"
    word_done: "✅"
    word_miss: "❌"
    test_done: "Тест закончен"
    no_packages: "У вас пока нет пакетов"
    choose_package: "Выберите пакет"
    insert_package: "Введите пары слов разделенные двоеточием, каждая пара слов должна быть на новой строке"
    insert_package_name: "Введите название пакета"
    added_package: "Пакет добавлен"
  errors:
    unknown_command: "Я не знаю такую команду"
    start_lesson: "Сначала начните урок"
    small_package: "Слишком маленький пакет. Пакет должен содеражать не менее 4 пар слов"
    empty_strings: "В пакете были найдены пустные строки, попробуйте ввести снова"
    already_exist: "Такой пакет уже существует"
    dosnt_work: "Пока не работает"
